version: "3.5"
services:
  db:
    image: postgres:latest
    command: postgres -c 'max_connections=400'
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    network_mode: host
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1.8GB"

  cache:
    hostname: cache
    image: redis:latest
    command: redis-server --save "" --appendonly no
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "0.2GB"

  api01: &api
    # image: zanfranceschi/rinha-api-2023
    build: ../
    depends_on:
      - db
      - cache
    environment:
      # https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector
      - DB_CONNECTION_STRING=Host=localhost;Username=admin;Password=123;Database=rinha;MaxPoolSize=60;
      - CACHE_CONNECTION_STRING=localhost
      - HTTP_PORT=8080
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "0.4GB"

  api02:
    <<: *api
    environment:
      # https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector
      - DB_CONNECTION_STRING=Host=localhost;Username=admin;Password=123;Database=rinha;MaxPoolSize=60;
      - CACHE_CONNECTION_STRING=cache
      - HTTP_PORT=8081

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "0.2GB"
